services:
    mc-botserver:
        image: mc-bot/botserver:latest
        build: .
        container_name: mc-botserver
        restart: unless-stopped
        networks:
            - mcbot
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - HOST=0.0.0.0
        volumes:
            - ./.env:/app/.env
            - ./Plugins:/app/Plugins
            - ./Resources:/app/Resources
            - ./Scripts:/app/Scripts
            - ./Logs:/app/Logs
            - ./Data:/app/Data

networks:
    mcbot:
        name: mc-bot
        external: true
